---
title: Future Immigration services
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Future immigrations services
  logo_img: "/images/Future Immigration Logo (4).png"
  has_nav: true
  menu:
    actions: []
footer:
  logo_img: ''
  tagline: ''
  has_nav: false
  nav_title: ''
  has_social: false
  social_title: ''
  has_subscribe: false
  subscribe_title: ''
  subscribe_content: ''
  content: ''
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
